### ISSUE TITLE
Cargar data de cada pais en data_paises.json

### ISSUE THREAD

**Issue by florlafuente** [lasdesistemas/figusdelaigualdad#1]
Hay que levantar la data de cada pais de este spreadsheet
https://docs.google.com/spreadsheets/d/161PnMp_ZU9BKgCRAgtPObIRwoWqRc_lWwkez1pZ1l4Q/edit#gid=745385378
Y devolverla como json

**Comment by naysolange** [comment]
Se creo el archivo data_paises.json en static/assets donde se debe cargar toda la info del spreadsheet en ese formato.

**Comment by guadix** [comment]
No hice un servicio, pero hice un parser. Puse PR para actualizar la data!

**Comment by naysolange** [comment]
gracias Guada! fijate que te respondí el PR

**Comment by guadix** [comment]
Ahí lo corregí!

**Comment by naysolange** [comment]
ya lo mergee a master!
