### ISSUE TITLE
Agregar en data_paises.json la licencia por paternidad

### ISSUE THREAD

**Issue by naysolange** [lasdesistemas/figusdelaigualdad#11]
Ahora el label dice: Días de licencia por maternidad/paternidad pero solo estamos mostrando los dias por maternidad.
Deberia quedar algo asi:

Días de licencia por maternidad/paternidad: 90/2

**Comment by naysolange** [comment]
Ya lo agregué en los grupos A, B, C y D. Falta en el resto.

**Comment by guadix** [comment]
No lo hagas a mano, lo puedo hacer con el parser!

**Comment by nportas** [comment]
es un toque igual! no te preocupes

**Comment by naysolange** [comment]
No te queria hinchar con el parser. Fijate si es simple y tenés ganas de hacerlo, sino yo mañana termino de cargar los que faltan, por hoy dejo acá.

**Comment by guadix** [comment]
Si, no era mucho, pero por las dudas. Asi queda por si lo tenemos que volver a correr! 

https://github.com/lasdesistemas/figusdelaigualdad/pull/12
