### ISSUE TITLE
Se ve mal la figu de Suiza

### ISSUE THREAD

**Issue by naysolange** [lasdesistemas/figusdelaigualdad#20]

**Comment by vnbarr** [comment]
@nportas @florlafuente che a mi se me siguen viendo mal, tendra q ver con la resolución o algo de eso? 
![captura de pantalla de 2018-06-26 16-59-30](https://user-images.githubusercontent.com/13315747/41936087-61d6e29c-7962-11e8-842e-3d0faaae9379.png)

**Comment by florlafuente** [comment]
Puede ser! Ahi chequeo. Decime por las dudas que navegador estás usando?

**Comment by vnbarr** [comment]
Google Chrome
Versión 65.0.3325.181

**Comment by naysolange** [comment]
yo la veo bien, que raro

**Comment by vnbarr** [comment]
lo cierro! solo me pasa en chrome pero a nadie más le pasó aún, así q no le daría bola
